package business.rules;

import com.hbg.otc.discounting.model.OrderLine;
import com.hbg.otc.discounting.model.Order;
import com.hbg.otc.discounting.model.Account;
import com.hbg.otc.discounting.model.Product;
import com.hbg.otc.discounting.model.RuleQualifier;
import com.hbg.otc.discounting.model.RuleSetup;
import java.util.*;
import java.lang.Integer;


rule "Check for Account Number / Product Group Code / Product ISBN"
	no-loop
    when  
	 	$o: Order($lines: orderLines)
       	$line: OrderLine($account: account, $product: product) from $lines
       	$ac: Account() from $account
       	$p: Product() from $product
       	$r: RuleSetup(account.accountNumber == $line.account.accountNumber || product.productGroupCode.equals($line.product.productGroupCode) || product.isbn == $line.product.isbn )
       	
   then  
     System.out.println($r.getRuleName() + " applied with discount: " + $r.getDiscount().getPercentage());
     
     List<RuleQualifier> ruleQualifierList = new ArrayList<RuleQualifier>();
     RuleQualifier ruleQualifier = new RuleQualifier();
     ruleQualifier.setRuleName($r.getRuleName());
     ruleQualifier.setRuleNumber($r.getRuleNumber());
     
     ruleQualifierList.add(ruleQualifier);
     $line.setRuleQualifier(ruleQualifierList);
     
end






